# Generated by Django 5.2.1 on 2025-06-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='yers',
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('first', 'Первый курс'), ('second', 'Второй курс'), ('third', 'Третий курс'), ('fourth', 'Четвертый курс')], default='first', max_length=6, verbose_name='Курс'),
        ),
    ]
