# Generated by Django 5.2.3 on 2025-07-01 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
