# Generated by Django 5.2.3 on 2025-07-01 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_mymodel_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='email',
            field=models.EmailField(default='no_email@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email студента'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2024, 1, 1), verbose_name='Дата зачисления'),
            preserve_default=False,
        ),
    ]
