# Generated by Django 5.2.3 on 2025-07-02 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_mymodel_email_student_email_student_enrollment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
