# Generated by Django 5.2.3 on 2025-07-02 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_mymodel_email_remove_mymodel_enrollment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
