"""
<<<<<<< HEAD
Django settings for config project. ⚙️

Для новичков:
Это мозг проекта - здесь хранятся все настройки! 🧠
- SECRET_KEY: Пароль проекта (как ключ от дома 🏡)
- DEBUG: Режим отладки (как каска на стройке 👷♂️)
- INSTALLED_APPS: Список установленных приложений (комнаты в доме 🚪)
- DATABASES: Настройки базы данных (библиотека с книгами-данными 📚)
- STATIC: Настройки статических файлов (CSS/JS - как мебель в доме 🛋️)
=======
Django settings for config project.
>>>>>>> 4c8d661fcdde86047e12f8fe9ea8ab23506eab11

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

<<<<<<< HEAD
import os
from dotenv import load_dotenv
from pathlib import Path

load_dotenv(override=True)

from django.forms.widgets import MEDIA_TYPES

=======
from pathlib import Path

>>>>>>> 4c8d661fcdde86047e12f8fe9ea8ab23506eab11
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
<<<<<<< HEAD
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv('DEBUG') == "True" else False
=======
SECRET_KEY = 'django-insecure-^9#wjpqn0k^uw^+rw8ko(h()s%vw#%4%#jyz%03(%(-c^txi40'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
>>>>>>> 4c8d661fcdde86047e12f8fe9ea8ab23506eab11

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'students',
]
=======
    'students',]
>>>>>>> 4c8d661fcdde86047e12f8fe9ea8ab23506eab11

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
<<<<<<< HEAD
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('NAME'),
        'USER': os.getenv('USER'),
        'PASSWORD': os.getenv('PASSWORD'),
        'HOST': os.getenv('HOST'),
        'PORT': os.getenv('PORT'),
=======
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
>>>>>>> 4c8d661fcdde86047e12f8fe9ea8ab23506eab11
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

<<<<<<< HEAD
LANGUAGE_CODE = 'ru-ru'
=======
LANGUAGE_CODE = 'en-us'
>>>>>>> 4c8d661fcdde86047e12f8fe9ea8ab23506eab11

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
<<<<<<< HEAD
STATICFILES_DIRS = (
    BASE_DIR / 'static',
)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
=======
>>>>>>> 4c8d661fcdde86047e12f8fe9ea8ab23506eab11

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
